// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/hong-l1/project/wire/repository"
	"github.com/hong-l1/project/wire/repository/Dao"
)

// Injectors from wire.go:

func InitRepository() *repository.UseRepository {
	db := InitDB()
	userDao := Dao.NewUserDao(db)
	useRepository := repository.NewUserRepository(userDao)
	return useRepository
}
